"""Transactional Fast-Weight Runtime (TFWR) / NPU hardware adapter.

This integration adapter demonstrates how an external learned or hardware-accelerated
scheduling runtime connects into the canonical UoW BaseProposer interface.

Invariant:
    Proposals generated by hardware accelerators or neural runtimes carry ZERO
    authority. All proposals must pass through the deterministic Judge and core
    certification before being materialized and committed.
"""
from __future__ import annotations

from typing import Any, Callable, Mapping, Optional, Sequence, Tuple

from uow.proposer.base import BaseProposer
from uow.proposer.heuristic import HeuristicSchedulingProposer
from uow.proposer.types import ModelProposal
from uow.state import WorldState


class TFWRRuntimeAdapter(BaseProposer):
    """Adapter wrapping an external TFWR / NPU runtime into a canonical BaseProposer.

    Accepts an optional hardware dispatch callable or inference client. If no external
    hardware client is attached, delegates proposal generation to the reference
    heuristic scheduling algorithm and explicitly labels the proposal as a portable
    reference fallback. A fallback is never labeled as hardware/NPU execution.
    """

    def __init__(
        self,
        hardware_client: Optional[Callable[..., Any]] = None,
        model_id: str = "TFWR_NPU_Scheduler",
        model_version: str = "2.0.0-npu-quantized",
        device_target: str = "NPU_ACCELERATED",
    ) -> None:
        self._client = hardware_client
        self._model_id = model_id
        self._version = model_version
        self._device_target = device_target
        self._fallback_heuristic = HeuristicSchedulingProposer(
            model_id=model_id, model_version=model_version
        )

    def model_id(self) -> str:
        return self._model_id

    def model_version(self) -> str:
        return self._version

    def propose(
        self,
        ready_candidates: Sequence[str],
        graph: Mapping[str, Any],
        state: WorldState,
    ) -> ModelProposal:
        """Emits a candidate schedule by querying the hardware client or reference heuristic."""
        if self._client is not None:
            raw_result = self._client(
                candidates=ready_candidates,
                graph=graph,
                state_hash=state.state_hash,
                sequence=state.sequence,
            )
            schedule = tuple(raw_result.get("candidate_schedule", ()))
            metrics = dict(raw_result.get("predicted_metrics", {}))
            meta = dict(raw_result.get("metadata", {}))
            meta.setdefault("device_target", self._device_target)
            meta.setdefault("backend", "TFWR")
            return ModelProposal(
                model_id=self.model_id(),
                model_version=self.model_version(),
                input_state_hash=state.state_hash,
                input_sequence=state.sequence,
                input_epoch=state.sequence,
                candidate_schedule=schedule,
                predicted_metrics=metrics,
                metadata=meta,
            )

        # Portable reference fallback. This path validates adapter/kernel
        # compatibility only; it is not TFWR/NPU hardware evidence.
        base_proposal = self._fallback_heuristic.propose(ready_candidates, graph, state)
        meta = dict(base_proposal.metadata)
        meta["device_target"] = "PORTABLE_REFERENCE"
        meta["backend"] = "REFERENCE_HEURISTIC"
        meta["substituted_for"] = self._device_target
        meta["hardware_executed"] = False
        return ModelProposal(
            model_id=self.model_id(),
            model_version=self.model_version(),
            input_state_hash=state.state_hash,
            input_sequence=state.sequence,
            input_epoch=state.sequence,
            candidate_schedule=base_proposal.candidate_schedule,
            predicted_metrics=dict(base_proposal.predicted_metrics),
            metadata=meta,
        )


TFWRAdapterProposer = TFWRRuntimeAdapter
