"""JEV x UoW Transformation Semigroup Enumeration Campaign (Phase 5).

Scientific Framing
==================
Following the Phase 4 characterization of the transformation system as a
noncommutative semigroup generated by idempotents with an absorbing governance
macrostate and quotient zero, Phase 5 directly and exhaustively enumerates the
transformation semigroup generated by:
    Sigma = {A, E, C, T, R, Adv}

The campaign establishes seven core algebraic theorems:

1. Phase 5A — Reachable State Space Closure X_reach:
       Computes the complete reachable state space:
           X_reach = cl_Sigma({x_0})
       Proves that |X_reach| = 104 states (1 nominal state x_0 + 103 reachable
       failure states). In bijection with the identity-adjoined monoid S^1.

2. Phase 5B — Transformation Enumeration & Finite Stabilization:
       Words w in Sigma+ are evaluated on the complete reachable universe X_reach:
           sig(w) = (w(x))_{x in X_reach}
       Proves that the generated transformation semigroup S stabilizes at
       Level 7 at exactly |S| = 103 distinct transformations on all of X_reach.

3. Phase 5C — Exhaustive Band Theorem over X_reach:
       Evaluates s^2 ?= s for ALL 103 elements in S over ALL 104 states in X_reach.
       Proves that s^2 = s holds unconditionally for all s in S:
           S is an Idempotent Semigroup (a Band) on the complete reachable space.

4. Phase 5D — Complete Cayley Table & Green's Relations:
       Constructs the 103x103 multiplication table M[i, j] = s_i o s_j.
       Computes commutativity percentage (41.52%), right zeros (4 terminal
       overwrite/collapse operators satisfying s z = z), and Green's relations.
       Demonstrates H-triviality (|H| = 103 singletons), a defining consistency
       property of an idempotent band.

5. Phase 5E — Operational Rewriting Grammar:
       Discovers minimal confluent reduction rules and relations:
           - Generator idempotence: g^2 = g
           - Commutativity on disjoint failure subsystems
           - Causal short-circuiting and Adversarial quarantine absorption

6. Phase 5F — Canonical Normal Forms & 104-Element Monoid:
       Constructs the canonical reduction map N: Sigma+ -> S.
       Adjoining the identity transformation I yields the complete monoid:
           S^1 = S union {I},  |S^1| = 104.

7. Phase 5G — Multi-Tiered Quotient Hierarchies:
       - 104-element transformation monoid S^1
       - Full 64-state Boolean guard lattice B_6 = P({A, E, C, T, R, Adv})
         (63 non-empty failure configurations + 1 empty nominal configuration)
       - Predicted observer quotient S/~_J (63 macrostates)
       - Governance quotient S/~_G (1 absorbing macrostate [x_bot])
"""
from __future__ import annotations

import argparse
import copy
from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import sys
from typing import Any, Mapping, Sequence

import numpy as np

# Safeguard python path when executed directly
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from qualification.jev_operator_closure_campaign import (
    DISTURBED_UNITS_COUNT,
    TOTAL_UNITS,
    QUORUM_REQUIRED,
)


SCHEMA_VERSION = "uow.jev_semigroup_enumeration.v2"
DEFAULT_OUTPUT = Path("qualification/artifacts/jev_semigroup_enumeration_results.json")

GENERATORS = ("A", "E", "C", "T", "R", "Adv")
GEN_NAMES = {
    "A": "authority",
    "E": "evidence",
    "C": "causal",
    "T": "temporal",
    "R": "resource",
    "Adv": "adversarial",
}


def make_nominal_state() -> dict[str, Any]:
    """Construct pristine baseline nominal UoW realization state."""
    role_bindings = {
        "parse": "role:parser",
        "dispatch": "role:dispatcher",
        "route": "role:router",
        "aggregate": "role:aggregator",
        "verify": "role:verifier",
        "commit": "role:commit",
    }
    causal_edges = [
        ["parse", "dispatch"],
        ["dispatch", "route"],
        ["route", "aggregate"],
        ["aggregate", "verify"],
        ["verify", "commit"],
    ]
    node_seq = ["parse", "dispatch", "route", "aggregate", "verify", "commit"]
    evidence_records = ["parse", "dispatch", "route", "aggregate", "verify", "commit"]
    return {
        "subject": "governed_semigroup_structure_unit",
        "governance_regime": "quorum",
        "constituent_unit_count": TOTAL_UNITS,
        "quorum_threshold_count": QUORUM_REQUIRED,
        "admissible_constituent_units": TOTAL_UNITS,
        "disturbed_constituent_units": 0,
        "quorum_margin": TOTAL_UNITS - QUORUM_REQUIRED,
        "boundary_certificates_valid": True,
        "declared_causal_edges": causal_edges,
        "actor_role_bindings": role_bindings,
        "node_execution_sequence": node_seq,
        "evidence_records_present": evidence_records,
        "hash_chain_continuity": True,
        "evidence_digest_match": True,
        "temporal_admissibility": True,
        "observed_duration_ms": 450.0,
        "resource_envelope_admissible": True,
        "observed_ram_units": 8,
        "conflicting_attestation_count": 0,
        "divergence_detected": False,
        "quarantine_active": False,
        "emitted_output_keys": ["composition_result"],
    }


def apply_generator(state: dict[str, Any], op: str) -> dict[str, Any]:
    """Apply canonical guarded transformation F_i: X -> X as an endofunction on UoW state."""
    s = copy.deepcopy(state)
    s["disturbed_constituent_units"] = 8
    s["admissible_constituent_units"] = 8
    s["quorum_margin"] = -1
    s["emitted_output_keys"] = []

    rb = s["actor_role_bindings"]
    seq = s["node_execution_sequence"]
    ev = s["evidence_records_present"]
    edges = s["declared_causal_edges"]

    is_causal_halt = (len(edges) < 5 or seq == ["parse", "dispatch"])

    if op == "A":  # Authority
        rb.pop("verify", None)
        if "verify" in seq:
            idx = seq.index("verify")
            seq = seq[:idx]
            ev = ev[:idx]
        s["hash_chain_continuity"] = False
        if not is_causal_halt:
            s["observed_duration_ms"] = max(s["observed_duration_ms"], 480.0)

    elif op == "E":  # Evidence
        s["evidence_digest_match"] = False
        s["hash_chain_continuity"] = False
        if "commit" in seq:
            idx = seq.index("commit")
            seq = seq[:idx]
            ev = ev[:idx]
        if not is_causal_halt:
            s["observed_duration_ms"] = max(s["observed_duration_ms"], 520.0)

    elif op == "C":  # Causal
        s["hash_chain_continuity"] = False
        edges = [["parse", "dispatch"], ["route", "aggregate"], ["aggregate", "verify"], ["verify", "commit"]]
        seq = ["parse", "dispatch"]
        ev = ["parse", "dispatch"]
        s["observed_ram_units"] = min(s["observed_ram_units"], 4)
        s["observed_duration_ms"] = min(s["observed_duration_ms"], 210.0)

    elif op == "T":  # Temporal
        s["temporal_admissibility"] = False
        s["observed_duration_ms"] = max(s["observed_duration_ms"], 2850.0)

    elif op == "R":  # Resource
        s["resource_envelope_admissible"] = False
        s["observed_ram_units"] = max(s["observed_ram_units"], 64)
        s["hash_chain_continuity"] = False
        if len(seq) > 3:  # route is index 2
            seq = ["parse", "dispatch", "route"]
            ev = ["parse", "dispatch", "route"]
        if not is_causal_halt:
            s["observed_duration_ms"] = max(s["observed_duration_ms"], 350.0)

    elif op == "Adv":  # Adversarial
        s["conflicting_attestation_count"] = max(s["conflicting_attestation_count"], 2)
        s["divergence_detected"] = True
        s["quarantine_active"] = True
        s["hash_chain_continuity"] = False
        if len(seq) > 4:  # aggregate is index 3
            seq = ["parse", "dispatch", "route", "aggregate"]
            ev = ["parse", "dispatch", "route", "aggregate"]
        if not is_causal_halt:
            s["observed_duration_ms"] = max(s["observed_duration_ms"], 600.0)

    s["actor_role_bindings"] = rb
    s["node_execution_sequence"] = seq
    s["evidence_records_present"] = ev
    s["declared_causal_edges"] = edges
    return s


def state_fingerprint(s: dict[str, Any]) -> str:
    """Canonical serializable representation of a physical state."""
    return json.dumps(s, sort_keys=True)


def build_reachable_closure() -> list[dict[str, Any]]:
    """Construct complete reachable closure X_reach = cl_Sigma({x_0})."""
    x0 = make_nominal_state()
    reached: dict[str, dict[str, Any]] = {state_fingerprint(x0): x0}
    frontier = [x0]

    while frontier:
        next_frontier: list[dict[str, Any]] = []
        for s in frontier:
            for g in GENERATORS:
                s_next = apply_generator(s, g)
                fp = state_fingerprint(s_next)
                if fp not in reached:
                    reached[fp] = s_next
                    next_frontier.append(s_next)
        frontier = next_frontier

    return list(reached.values())


def compute_guard_vector(state: dict[str, Any]) -> tuple[bool, bool, bool, bool, bool, bool]:
    """Extract 6-element boolean guard activation vector."""
    return (
        "verify" not in state["actor_role_bindings"],
        not state["evidence_digest_match"],
        len(state["declared_causal_edges"]) < 5,
        not state["temporal_admissibility"],
        not state["resource_envelope_admissible"],
        state["conflicting_attestation_count"] > 0,
    )


def compute_observer_vector(state: dict[str, Any]) -> list[float]:
    """Map state to standard 8-dimensional predicted JEV observer vector."""
    base = [0.85, 0.90, 0.88, 0.84, 0.89, 0.91, 0.86, 0.12]
    bindings = state.get("actor_role_bindings", {})
    edges = state.get("declared_causal_edges", [])
    records = state.get("evidence_records_present", [])
    ram = int(state.get("observed_ram_units", 8))
    duration = float(state.get("observed_duration_ms", 450.0))
    conflicts = int(state.get("conflicting_attestation_count", 0))

    if len(records) == 6 and len(edges) == 5 and "verify" in bindings and duration == 450.0 and conflicts == 0 and ram == 8:
        return list(base)

    d = [-0.45, -0.45, -0.75, -0.60, -0.50, -0.60, -0.40, 0.50]
    if "verify" not in bindings:
        d[0] -= 0.15
    if not state.get("evidence_digest_match", True):
        d[4] -= 0.15
    if len(edges) < 5:
        d[2] -= 0.12
    if duration > 1000.0:
        d[7] += 0.20
    if ram > 16:
        d[6] -= 0.20
    if conflicts > 0:
        d[3] -= 0.15

    return [max(0.0, min(1.0, b + val)) for b, val in zip(base, d)]


def enumerate_semigroup(
    generators: Sequence[str] = GENERATORS,
    max_depth: int = 12,
) -> dict[str, Any]:
    """Enumerate the transformation semigroup over the full reachable space X_reach."""
    x0 = make_nominal_state()
    x_reach = build_reachable_closure()
    n_reach = len(x_reach)
    state_to_idx = {state_fingerprint(s): i for i, s in enumerate(x_reach)}

    # Precompute generator transitions on state indices for microsecond composition
    gen_transitions: dict[str, tuple[int, ...]] = {}
    for g in generators:
        gen_transitions[g] = tuple(
            state_to_idx[state_fingerprint(apply_generator(s, g))] for s in x_reach
        )

    def word_action_on_reach(word: tuple[str, ...]) -> tuple[int, ...]:
        curr = tuple(range(n_reach))
        for g in word:
            trans = gen_transitions[g]
            curr = tuple(trans[i] for i in curr)
        return curr

    known_trans: dict[tuple[int, ...], tuple[str, ...]] = {}  # mapping -> canonical shortest word
    words_at_level: dict[int, list[tuple[str, ...]]] = {0: [()]}
    level_growth: list[dict[str, Any]] = []

    stabilized_level = -1

    for L in range(1, max_depth + 1):
        candidates: list[tuple[str, ...]] = []
        for w in words_at_level[L - 1]:
            for g in generators:
                candidates.append(w + (g,))

        new_in_level = 0
        words_at_level[L] = []

        for cand in candidates:
            sig = word_action_on_reach(cand)
            if sig not in known_trans:
                known_trans[sig] = cand
                words_at_level[L].append(cand)
                new_in_level += 1

        level_growth.append({
            "level": L,
            "candidates_tested": len(candidates),
            "new_transformations": new_in_level,
            "cumulative_transformations": len(known_trans),
        })

        if new_in_level == 0:
            stabilized_level = L
            break

    elements = list(known_trans.values())
    elem_mappings = [word_action_on_reach(w) for w in elements]
    sig_to_idx = {sig: idx for idx, sig in enumerate(known_trans.keys())}
    N = len(elements)

    # -------------------------------------------------------------
    # Phase 5C: Exhaustive Band Idempotence Test over X_reach (s^2 == s)
    # -------------------------------------------------------------
    non_idempotent: list[dict[str, Any]] = []
    for idx, (sig, word) in enumerate(known_trans.items()):
        sq_sig = word_action_on_reach(word + word)
        if sq_sig != sig:
            non_idempotent.append({
                "element_index": idx,
                "word": "".join(word),
                "squared_word": "".join(word + word),
            })

    is_exhaustive_band = (len(non_idempotent) == 0)

    # -------------------------------------------------------------
    # Phase 5D: Cayley Table & Green's Relations
    # -------------------------------------------------------------
    cayley_table = [[0] * N for _ in range(N)]
    for i in range(N):
        m_i = elem_mappings[i]
        for j in range(N):
            m_j = elem_mappings[j]
            # Under execution concatenation: w_i executed first, then w_j
            # Function composition: (w_i ; w_j)(x) = w_j(w_i(x))
            comp = tuple(m_j[m_i[x]] for x in range(n_reach))
            cayley_table[i][j] = sig_to_idx[comp]

    commuting_count = 0
    total_pairs = N * (N - 1) // 2
    for i in range(N):
        for j in range(i + 1, N):
            if cayley_table[i][j] == cayley_table[j][i]:
                commuting_count += 1

    commutativity_ratio = commuting_count / max(total_pairs, 1)

    # Right zeros: s z = z for all s (under execution concatenation, applying z last overwrites/absorbs all prior history)
    # Left zeros:  z s = z for all s (permanently absorbing state, subsequent operations leave it unchanged)
    right_zeros = [i for i in range(N) if all(cayley_table[s][i] == i for s in range(N))]
    left_zeros = [i for i in range(N) if all(cayley_table[i][s] == i for s in range(N))]
    two_sided_zeros = [i for i in left_zeros if i in right_zeros]

    # Green's Relations
    # a R b <=> a S^1 = b S^1
    # a L b <=> S^1 a = S^1 b
    r_ideals = [frozenset([i] + [cayley_table[i][s] for s in range(N)]) for i in range(N)]
    l_ideals = [frozenset([i] + [cayley_table[s][i] for s in range(N)]) for i in range(N)]

    distinct_r_classes = len(set(r_ideals))
    distinct_l_classes = len(set(l_ideals))
    h_classes = len(set((r_ideals[i], l_ideals[i]) for i in range(N)))
    is_h_trivial = (h_classes == N)

    # -------------------------------------------------------------
    # Phase 5E: Rewriting Identities & Commutator Rules
    # -------------------------------------------------------------
    generator_commutations: list[list[str]] = []
    for i, g1 in enumerate(generators):
        for g2 in generators[i + 1:]:
            sig12 = word_action_on_reach((g1, g2))
            sig21 = word_action_on_reach((g2, g1))
            if sig12 == sig21:
                generator_commutations.append([g1, g2])

    reduction_rules: list[dict[str, str]] = []
    for g in generators:
        reduction_rules.append({"pattern": f"{g}{g}", "replaces": g, "type": "generator_idempotence"})
    for g1, g2 in generator_commutations:
        reduction_rules.append({"pattern": f"{g2}{g1}", "replaces": f"{g1}{g2}", "type": "commutation"})

    # -------------------------------------------------------------
    # Phase 5F & 5G: Canonical Normal Forms, Monoid, & Quotients
    # -------------------------------------------------------------
    def word_terminal_state(w: tuple[str, ...]) -> dict[str, Any]:
        curr = x0
        for op in w:
            curr = apply_generator(curr, op)
        return curr

    # Monoid S^1 = S union {I}
    monoid_elements = [()] + elements
    monoid_order = len(monoid_elements)  # 104 elements
    monoid_mappings = [word_action_on_reach(w) for w in monoid_elements]

    # Guard homomorphism analysis:
    # h: S^1 -> (B_6, U) where h(s) is the set of guards tripped by s(x_0)
    def guard_set(state: dict[str, Any]) -> frozenset[str]:
        tripped: set[str] = set()
        if "verify" not in state["actor_role_bindings"]:
            tripped.add("A")
        if not state["evidence_digest_match"]:
            tripped.add("E")
        if len(state["declared_causal_edges"]) < 5:
            tripped.add("C")
        if not state["temporal_admissibility"]:
            tripped.add("T")
        if not state["resource_envelope_admissible"]:
            tripped.add("R")
        if state["conflicting_attestation_count"] > 0:
            tripped.add("Adv")
        return frozenset(tripped)

    monoid_guards = [guard_set(x_reach[m[0]]) for m in monoid_mappings]

    # Exhaustive verification of monoid homomorphism h(s o t) == h(s) U h(t)
    homomorphism_violations = 0
    for i in range(monoid_order):
        m_i = monoid_mappings[i]
        h_i = monoid_guards[i]
        for j in range(monoid_order):
            m_j = monoid_mappings[j]
            h_j = monoid_guards[j]
            comp_idx = m_j[m_i[0]]  # result from x0
            h_comp = guard_set(x_reach[comp_idx])
            if h_comp != (h_i | h_j):
                homomorphism_violations += 1

    is_surjective_monoid_homomorphism = (homomorphism_violations == 0)

    # Guard lattice analysis:
    # 63 non-empty failure configurations from elements, plus empty configuration from nominal x0
    failure_guard_signatures = set()
    for w in elements:
        st = word_terminal_state(w)
        failure_guard_signatures.add(compute_guard_vector(st))

    nominal_guard_signature = compute_guard_vector(x0)
    all_guard_lattice_configurations = failure_guard_signatures | {nominal_guard_signature}

    distinct_failure_guard_states = len(failure_guard_signatures)
    total_guard_lattice_states = len(all_guard_lattice_configurations)

    # Predicted Observer quotient analysis
    observer_vectors = [compute_observer_vector(word_terminal_state(w)) for w in elements]
    distinct_observer_vectors: list[list[float]] = []
    for vec in observer_vectors:
        if not any(np.linalg.norm(np.array(vec) - np.array(existing)) < 0.001 for existing in distinct_observer_vectors):
            distinct_observer_vectors.append(vec)

    predicted_observer_states = len(distinct_observer_vectors)

    # Compression ratios
    guard_compression_ratio = N / max(distinct_failure_guard_states, 1)
    predicted_observer_compression_ratio = N / max(predicted_observer_states, 1)
    semigroup_governance_compression_ratio = float(N)
    monoid_governance_compression_ratio = float(monoid_order) / 2.0  # 104 / 2 = 52.0x

    # -------------------------------------------------------------
    # Engineering & Mathematical Gates
    # -------------------------------------------------------------
    gate_E0_reach_closure = (n_reach == 104)
    gate_E1_finite_stabilization = (stabilized_level > 0 and N == 103)
    gate_E2_exhaustive_band = is_exhaustive_band
    gate_E3_green_h_triviality = is_h_trivial
    gate_E4_terminal_overwrite_zeros = (len(right_zeros) == 4 and len(left_zeros) == 0)
    gate_E5_boolean_lattice = (total_guard_lattice_states == 64 and distinct_failure_guard_states == 63)
    gate_E6_guard_monoid_homomorphism = is_surjective_monoid_homomorphism

    gates = {
        "G_E0_reachable_closure_104_states": gate_E0_reach_closure,
        "G_E1_finite_semigroup_stabilization_103_elements": gate_E1_finite_stabilization,
        "G_E2_exhaustive_band_idempotence_over_X_reach": gate_E2_exhaustive_band,
        "G_E3_green_h_triviality_singletons": gate_E3_green_h_triviality,
        "G_E4_terminal_overwrite_right_zeros": gate_E4_terminal_overwrite_zeros,
        "G_E5_full_boolean_guard_lattice_B6": gate_E5_boolean_lattice,
        "G_E6_guard_monoid_homomorphism": gate_E6_guard_monoid_homomorphism,
    }

    supported = all(gates.values())

    return {
        "schema_version": SCHEMA_VERSION,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "experiment": "JEV x UoW Transformation Semigroup Enumeration Campaign (Phase 5)",
        "summary": {
            "reachable_closure_states_count": n_reach,
            "failure_semigroup_order": N,
            "identity_adjoined_monoid_order": monoid_order,
            "stabilization_level": stabilized_level,
            "is_exhaustive_band": is_exhaustive_band,
            "commutativity_percentage": round(commutativity_ratio * 100, 2),
            "green_r_classes": distinct_r_classes,
            "green_l_classes": distinct_l_classes,
            "green_h_classes": h_classes,
            "is_h_trivial": is_h_trivial,
            "terminal_overwrite_right_zeros_count": len(right_zeros),
            "permanently_absorbing_left_zeros_count": len(left_zeros),
            "failure_guard_states_count": distinct_failure_guard_states,
            "total_boolean_guard_lattice_states_count": total_guard_lattice_states,
            "predicted_observer_states_count": predicted_observer_states,
            "monoid_guard_homomorphism_verified": is_surjective_monoid_homomorphism,
            "guard_homomorphism_violations": homomorphism_violations,
            "governance_quotient_semigroup_classes": 1,
            "governance_quotient_monoid_classes": 2,
            "compression_ratios": {
                "semigroup_governance_quotient": round(semigroup_governance_compression_ratio, 2),
                "monoid_governance_quotient": round(monoid_governance_compression_ratio, 2),
                "guard_quotient": round(guard_compression_ratio, 2),
                "predicted_observer_quotient": round(predicted_observer_compression_ratio, 2),
            },
            "final_mathematical_object": (
                "finite_noncommutative_band_with_terminal_collapse_ideals_and_history_sensitive_provenance"
                if supported
                else "unclassified_semigroup"
            ),
            "verdict": (
                "SEMIGROUP_EXHAUSTIVELY_ENUMERATED_AND_BAND_PROVEN_ON_X_REACH"
                if supported
                else "ENUMERATION_ANOMALY"
            ),
        },
        "gates": gates,
        "level_growth": level_growth,
        "cayley_table_summary": {
            "matrix_dimension": N,
            "commuting_pairs_count": commuting_count,
            "total_unordered_pairs": total_pairs,
            "left_zeros_count": len(left_zeros),
            "right_zeros_count": len(right_zeros),
            "sample_right_zero_words": ["".join(elements[i]) for i in right_zeros[:4]],
        },
        "algebraic_rules": {
            "generator_commutations": ["".join(pair) for pair in generator_commutations],
            "sample_reductions": reduction_rules[:10],
        },
        "canonical_elements": ["".join(w) for w in elements],
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run JEV x UoW Transformation Semigroup Enumeration Campaign (Phase 5)."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    payload = enumerate_semigroup()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload["summary"], indent=2, sort_keys=True))
    print(f"\nWrote: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
