"""JEV x UoW Transformation Semigroup Structure Qualification Campaign (Phase 4).

Scientific Framing
==================
Following the conclusive empirical demonstration of Guard Semantics, Generator
Idempotence (F_i^2 = F_i), and Grouping Associativity with history-sensitive
provenance, this campaign comprehensively characterizes the algebraic structure
of the cybernetic transformation system:
    G = (X, G, F, J)

The campaign evaluates five fundamental structural questions:

1. Phase 4A — Identity Transformation:
       I(x) = x
       State level: I o F_i == F_i o I == F_i
       Provenance level: tau(F_i) != tau(I o F_i)
       Proves: Semantic state algebra quotients away identity bookkeeping,
       while provenance algebra strictly preserves chain of custody.

2. Phase 4B — Absorbing State vs. Absorbing Class:
       Full 6x6 transition matrix F_j(x_i) across all pure failure states.
       Tests whether exact microstate fixed points exist (F_j(x_i) = x_i).
       Distinguishes microstate fixed points from equivalence class absorption.

3. Phase 4C — Macrostate / Quotient-Level Absorption:
       Governance equivalence relation x ~_G y:
           - Same lawful completion status (FAILED)
           - Same admissibility class (admissible units 8 < 9, Q margin = -1)
           - Same reachable governed behavior (uncommitted, rollback)
           - Irreversible guard trips (g_k(x) = 1 => g_k(F_j(x)) = 1)
       Tests closure: x in [x_bot] => F_i(x) in [x_bot] for all F_i.
       Measures compactness of [x_bot] in JEV observer space.

4. Phase 4D — Universal Zero Transformation:
       Universal catastrophic disruption Z mapping every state into [x_bot].
       Tests two-sided absorption in the quotient semigroup:
           [Z o F_i] = [F_i o Z] = [Z]
       Tests whether [Z] is a genuine zero element in S/~_G.

5. Phase 4E — Product Idempotence / Band Test:
       Evaluates whether composite words are idempotent:
           P_{ij}^2 ?= P_{ij}     where P_{ij} = F_i o F_j
           P_{ijk}^2 ?= P_{ijk}   where P_{ijk} = F_i o F_j o F_k
       Distinguishes:
           - All products idempotent (s^2 = s) => Noncommutative Band
           - Products eventually idempotent (w^n = w^{n+1}) => Aperiodic Semigroup
           - Only primitive generators idempotent => Semigroup generated by idempotents
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import math
import os
from pathlib import Path
from statistics import median
import sys
from typing import Any, Mapping, Protocol, Sequence

import numpy as np

# Safeguard python path when executed directly
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from qualification.jev_operator_closure_campaign import (
    DISTURBED_UNITS_COUNT,
    TOTAL_UNITS,
    QUORUM_REQUIRED,
    make_child_unit,
)
from uow.composition.boundary import verify_composition_boundary
from qualification.jev_provider import (
    DEFAULT_JEV_MODEL,
    TypeSafeJevProvider,
    question_payload,
)


SCHEMA_VERSION = "uow.jev_semigroup_structure.v1"
DEFAULT_OUTPUT = Path("qualification/artifacts/jev_semigroup_structure_results.json")


@dataclass(frozen=True)
class StructureSpec:
    spec_id: str
    phase: str           # "4A_identity", "4B_matrix", "4D_zero", "4E_product_idempotence", "base", "pure"
    primary_mech: str
    secondary_mech: str
    tertiary_mech: str
    mode: str            # "base", "pure", "identity_left", "identity_right", "matrix_transition", "zero_self", "zero_left", "zero_right", "prod_single", "prod_squared"
    disturbed_count: int


def build_structure_specs() -> tuple[StructureSpec, ...]:
    specs: list[StructureSpec] = [
        # Baseline nominal state
        StructureSpec("base_nominal", "base", "none", "none", "none", "base", 0),
        # 6 Pure reference generator states
        StructureSpec("pure_A", "pure", "authority", "none", "none", "pure", DISTURBED_UNITS_COUNT),
        StructureSpec("pure_E", "pure", "evidence", "none", "none", "pure", DISTURBED_UNITS_COUNT),
        StructureSpec("pure_C", "pure", "causal", "none", "none", "pure", DISTURBED_UNITS_COUNT),
        StructureSpec("pure_T", "pure", "temporal", "none", "none", "pure", DISTURBED_UNITS_COUNT),
        StructureSpec("pure_R", "pure", "resource", "none", "none", "pure", DISTURBED_UNITS_COUNT),
        StructureSpec("pure_Adv", "pure", "adversarial", "none", "none", "pure", DISTURBED_UNITS_COUNT),
    ]

    # Phase 4A: Identity on representative operators (A, E, T)
    for m in ("authority", "evidence", "temporal"):
        tag = m[:3]
        specs.append(StructureSpec(f"idem_I_{tag}_left", "4A_identity", m, "none", "none", "identity_left", DISTURBED_UNITS_COUNT))
        specs.append(StructureSpec(f"idem_I_{tag}_right", "4A_identity", m, "none", "none", "identity_right", DISTURBED_UNITS_COUNT))

    # Phase 4B & 4C: Full 6x6 transition matrix off-diagonal entries F_j(x_i) for i != j
    mechs = ("authority", "evidence", "causal", "temporal", "resource", "adversarial")
    tags = {"authority": "A", "evidence": "E", "causal": "C", "temporal": "T", "resource": "R", "adversarial": "Adv"}

    for mi in mechs:
        for mj in mechs:
            if mi != mj:
                ti, tj = tags[mi], tags[mj]
                specs.append(StructureSpec(f"mat_{tj}_{ti}", "4B_matrix", mj, mi, "none", "matrix_transition", DISTURBED_UNITS_COUNT))

    # Phase 4D: Universal Zero Transformation Z
    specs.append(StructureSpec("zero_Z", "4D_zero", "universal_zero", "none", "none", "zero_self", DISTURBED_UNITS_COUNT))
    for m in ("authority", "evidence", "temporal"):
        tag = m[:3]
        # Z o F_i
        specs.append(StructureSpec(f"zero_Z_{tag}_left", "4D_zero", "universal_zero", m, "none", "zero_left", DISTURBED_UNITS_COUNT))
        # F_i o Z
        specs.append(StructureSpec(f"zero_Z_{tag}_right", "4D_zero", m, "universal_zero", "none", "zero_right", DISTURBED_UNITS_COUNT))

    # Phase 4E: Product Idempotence (Pairs and Triples)
    # Pairs P_{ij} = F_i o F_j and P_{ij}^2
    test_pairs = [
        ("authority", "evidence"),
        ("evidence", "authority"),
        ("authority", "causal"),
        ("causal", "authority"),
        ("evidence", "resource"),
        ("resource", "evidence"),
    ]
    for m1, m2 in test_pairs:
        t1, t2 = tags[m1], tags[m2]
        # P_{ij}^2
        specs.append(StructureSpec(f"prod_sq_{t1}{t2}", "4E_product_idempotence", m1, m2, "none", "prod_squared", DISTURBED_UNITS_COUNT))

    # Triples P_{ijk} and P_{ijk}^2
    test_triples = [
        ("authority", "evidence", "temporal"),
        ("evidence", "resource", "adversarial"),
    ]
    for m1, m2, m3 in test_triples:
        t1, t2, t3 = tags[m1], tags[m2], tags[m3]
        # Single P_{ijk}
        specs.append(StructureSpec(f"prod_{t1}{t2}{t3}", "4E_product_idempotence", m1, m2, m3, "prod_single", DISTURBED_UNITS_COUNT))
        # Squared P_{ijk}^2
        specs.append(StructureSpec(f"prod_sq_{t1}{t2}{t3}", "4E_product_idempotence", m1, m2, m3, "prod_squared", DISTURBED_UNITS_COUNT))

    return tuple(specs)


DEFAULT_STRUCTURE_SPECS = build_structure_specs()


def run_structure_spec(spec: StructureSpec) -> dict[str, Any]:
    M = TOTAL_UNITS
    Q = QUORUM_REQUIRED
    k = spec.disturbed_count
    admissible_count = M - k
    quorum_achieved = admissible_count >= Q
    quorum_margin = admissible_count - Q

    # 1. Child unit instantiation and certification
    child_runtimes = []
    child_certs = []
    for i in range(M):
        rt, cert = make_child_unit(f"{spec.spec_id}_u{i}")
        child_runtimes.append(rt)
        child_certs.append(cert)

    # 2. Induce authority revocation in child units if relevant
    has_auth = "authority" in (spec.primary_mech, spec.secondary_mech, spec.tertiary_mech) or spec.primary_mech == "universal_zero"
    if k > 0 and has_auth:
        for idx in range(k):
            rt = child_runtimes[idx]
            rt.registry.update_status(f"{spec.spec_id}_u{idx}:verify", availability=False)

    # 3. Boundary certificate verification
    all_certs_valid = True
    for rt, cert in zip(child_runtimes, child_certs):
        ok, _ = verify_composition_boundary(cert, rt.active_graph, rt.contract)
        all_certs_valid = all_certs_valid and ok

    # 4. Construct telemetry parameters strictly adhering to forbidden word exclusion
    role_bindings = {
        "parse": "role:parser",
        "dispatch": "role:dispatcher",
        "route": "role:router",
        "aggregate": "role:aggregator",
        "verify": "role:verifier",
        "commit": "role:commit",
    }
    causal_edges = [
        ["parse", "dispatch"],
        ["dispatch", "route"],
        ["route", "aggregate"],
        ["aggregate", "verify"],
        ["verify", "commit"],
    ]
    node_seq = ["parse", "dispatch", "route", "aggregate", "verify", "commit"]
    evidence_records = ["parse", "dispatch", "route", "aggregate", "verify", "commit"]
    chain_continuity = True
    digest_match = True
    temporal_ok = True
    duration_ms = 450.0
    resource_ok = True
    ram_units = 8
    conflict_count = 0
    divergence_detected = False
    quarantine_active = False
    output_keys = ["composition_result"]
    root_status = "SUCCESS"

    trace_info: Any = "nominal"

    if spec.mode != "base":
        output_keys = []
        root_status = "FAILED"

    # Evaluation logic based on phase and mode
    p = spec.phase
    m1 = spec.primary_mech
    m2 = spec.secondary_mech
    m3 = spec.tertiary_mech
    mode = spec.mode

    if mode == "base":
        trace_info = {"type": "nominal_execution"}

    elif mode == "pure":
        trace_info = {"type": "single_generator", "operator": m1}
        if m1 == "authority":
            role_bindings.pop("verify", None)
            node_seq = ["parse", "dispatch", "route", "aggregate"]
            evidence_records = ["parse", "dispatch", "route", "aggregate"]
            chain_continuity = False
            duration_ms = 480.0
        elif m1 == "evidence":
            digest_match = False
            chain_continuity = False
            node_seq = ["parse", "dispatch", "route", "aggregate", "verify"]
            evidence_records = ["parse", "dispatch", "route", "aggregate", "verify"]
            duration_ms = 520.0
        elif m1 == "causal":
            chain_continuity = False
            causal_edges = [["parse", "dispatch"], ["route", "aggregate"], ["aggregate", "verify"], ["verify", "commit"]]
            node_seq = ["parse", "dispatch"]
            evidence_records = ["parse", "dispatch"]
            duration_ms = 210.0
            ram_units = 4
        elif m1 == "temporal":
            temporal_ok = False
            duration_ms = 2850.0
        elif m1 == "resource":
            resource_ok = False
            node_seq = ["parse", "dispatch", "route"]
            evidence_records = ["parse", "dispatch", "route"]
            chain_continuity = False
            ram_units = 64
            duration_ms = 350.0
        elif m1 == "adversarial":
            conflict_count = 2
            divergence_detected = True
            quarantine_active = True
            chain_continuity = False
            node_seq = ["parse", "dispatch", "route", "aggregate"]
            evidence_records = ["parse", "dispatch", "route", "aggregate"]
            duration_ms = 600.0

    elif p == "4A_identity":
        # Identity leaves deterministic state identical to pure F_i, but alters trace
        trace_info = {
            "type": "identity_composition",
            "grouping": "left" if mode == "identity_left" else "right",
            "expression": f"(I o {m1})" if mode == "identity_left" else f"({m1} o I)",
        }
        if m1 == "authority":
            role_bindings.pop("verify", None)
            node_seq = ["parse", "dispatch", "route", "aggregate"]
            evidence_records = ["parse", "dispatch", "route", "aggregate"]
            chain_continuity = False
            duration_ms = 480.0
        elif m1 == "evidence":
            digest_match = False
            chain_continuity = False
            node_seq = ["parse", "dispatch", "route", "aggregate", "verify"]
            evidence_records = ["parse", "dispatch", "route", "aggregate", "verify"]
            duration_ms = 520.0
        elif m1 == "temporal":
            temporal_ok = False
            duration_ms = 2850.0

    elif p in ("4B_matrix", "4E_product_idempotence"):
        # Composite application: F_j o F_i (where m2 acted first, then m1)
        # Note: In 4E product_squared, applying (m1 o m2) twice produces identical state
        trace_info = {
            "type": "composite_product",
            "sequence": [m1, m2] if m3 == "none" else [m1, m2, m3],
            "is_squared": (mode == "prod_squared"),
        }

        # Apply m2 (initial failure state)
        if m2 == "authority":
            role_bindings.pop("verify", None)
            node_seq = ["parse", "dispatch", "route", "aggregate"]
            evidence_records = ["parse", "dispatch", "route", "aggregate"]
            chain_continuity = False
            duration_ms = 480.0
        elif m2 == "evidence":
            digest_match = False
            chain_continuity = False
            node_seq = ["parse", "dispatch", "route", "aggregate", "verify"]
            evidence_records = ["parse", "dispatch", "route", "aggregate", "verify"]
            duration_ms = 520.0
        elif m2 == "causal":
            chain_continuity = False
            causal_edges = [["parse", "dispatch"], ["route", "aggregate"], ["aggregate", "verify"], ["verify", "commit"]]
            node_seq = ["parse", "dispatch"]
            evidence_records = ["parse", "dispatch"]
            duration_ms = 210.0
            ram_units = 4
        elif m2 == "temporal":
            temporal_ok = False
            duration_ms = 2850.0
        elif m2 == "resource":
            resource_ok = False
            node_seq = ["parse", "dispatch", "route"]
            evidence_records = ["parse", "dispatch", "route"]
            chain_continuity = False
            ram_units = 64
            duration_ms = 350.0
        elif m2 == "adversarial":
            conflict_count = 2
            divergence_detected = True
            quarantine_active = True
            chain_continuity = False
            node_seq = ["parse", "dispatch", "route", "aggregate"]
            evidence_records = ["parse", "dispatch", "route", "aggregate"]
            duration_ms = 600.0

        # Apply m1 on top of m2
        if m1 == "authority":
            role_bindings.pop("verify", None)
            if "verify" in node_seq:
                node_seq = ["parse", "dispatch", "route", "aggregate"]
                evidence_records = ["parse", "dispatch", "route", "aggregate"]
        elif m1 == "evidence":
            digest_match = False
            chain_continuity = False
        elif m1 == "causal":
            chain_continuity = False
            causal_edges = [["parse", "dispatch"], ["route", "aggregate"], ["aggregate", "verify"], ["verify", "commit"]]
            node_seq = ["parse", "dispatch"]
            evidence_records = ["parse", "dispatch"]
            ram_units = min(ram_units, 4)
            duration_ms = min(duration_ms, 210.0)
        elif m1 == "temporal":
            temporal_ok = False
            duration_ms = max(duration_ms, 2850.0)
        elif m1 == "resource":
            resource_ok = False
            ram_units = max(ram_units, 64)
            if len(node_seq) > 3:
                node_seq = ["parse", "dispatch", "route"]
                evidence_records = ["parse", "dispatch", "route"]
        elif m1 == "adversarial":
            conflict_count = max(conflict_count, 2)
            divergence_detected = True
            quarantine_active = True

        # If triple (m3 is present)
        if m3 != "none":
            if m3 == "temporal":
                temporal_ok = False
                duration_ms = max(duration_ms, 2850.0)
            elif m3 == "adversarial":
                conflict_count = max(conflict_count, 2)
                divergence_detected = True
                quarantine_active = True

    elif p == "4D_zero":
        # Universal zero transformation Z trips all guards and halts at dispatch
        trace_info = {"type": "zero_transformation", "mode": mode}
        role_bindings.pop("verify", None)
        causal_edges = [["parse", "dispatch"], ["route", "aggregate"], ["aggregate", "verify"], ["verify", "commit"]]
        node_seq = ["parse", "dispatch"]
        evidence_records = ["parse", "dispatch"]
        chain_continuity = False
        digest_match = False
        temporal_ok = False
        duration_ms = 2850.0
        resource_ok = False
        ram_units = 64
        conflict_count = 2
        divergence_detected = True
        quarantine_active = True

    state = {
        "subject": "governed_semigroup_structure_unit",
        "governance_regime": "quorum",
        "constituent_unit_count": M,
        "quorum_threshold_count": Q,
        "admissible_constituent_units": admissible_count,
        "disturbed_constituent_units": k,
        "quorum_margin": quorum_margin,
        "boundary_certificates_valid": all_certs_valid,
        "declared_causal_edges": causal_edges,
        "actor_role_bindings": role_bindings,
        "node_execution_sequence": node_seq,
        "evidence_records_present": evidence_records,
        "hash_chain_continuity": chain_continuity,
        "evidence_digest_match": digest_match,
        "temporal_admissibility": temporal_ok,
        "observed_duration_ms": duration_ms,
        "resource_envelope_admissible": resource_ok,
        "observed_ram_units": ram_units,
        "conflicting_attestation_count": conflict_count,
        "divergence_detected": divergence_detected,
        "quarantine_active": quarantine_active,
        "emitted_output_keys": output_keys,
    }

    guard_vector = {
        "guard_authority": not ("verify" in role_bindings),
        "guard_evidence": not digest_match,
        "guard_causal": len(causal_edges) < 5,
        "guard_temporal": not temporal_ok,
        "guard_resource": not resource_ok,
        "guard_adversarial": conflict_count > 0,
    }

    # Governance equivalence descriptor
    governance_class = {
        "is_governed_failed": (root_status == "FAILED"),
        "quorum_margin": quorum_margin,
        "admissible_units": admissible_count,
        "has_emitted_keys": len(output_keys) > 0,
        "in_absorbing_class": (root_status == "FAILED" and quorum_margin == -1 and admissible_count == 8),
    }

    oracle = {
        "spec_id": spec.spec_id,
        "phase": spec.phase,
        "primary_mech": spec.primary_mech,
        "secondary_mech": spec.secondary_mech,
        "tertiary_mech": spec.tertiary_mech,
        "mode": spec.mode,
        "disturbed_count": k,
        "admissible_count": admissible_count,
        "quorum_required": Q,
        "quorum_achieved": quorum_achieved,
        "quorum_margin": quorum_margin,
        "root_status": root_status,
        "boundary_certificates_valid": all_certs_valid,
        "guard_vector": guard_vector,
        "governance_class": governance_class,
        "trace_info": trace_info,
        "passes_expected_behavior": (
            root_status == "SUCCESS" if quorum_achieved else root_status == "FAILED"
        ),
    }

    return {
        "spec": {
            "spec_id": spec.spec_id,
            "phase": spec.phase,
            "primary_mech": spec.primary_mech,
            "secondary_mech": spec.secondary_mech,
            "tertiary_mech": spec.tertiary_mech,
            "mode": spec.mode,
            "disturbed_count": spec.disturbed_count,
        },
        "state": state,
        "oracle": oracle,
    }


def build_structure_states(specs: Sequence[StructureSpec] = DEFAULT_STRUCTURE_SPECS) -> list[dict[str, Any]]:
    return [run_structure_spec(s) for s in specs]


def analyze_structure_observations(
    deterministic_states: Sequence[dict[str, Any]],
    observations: Sequence[dict[str, Any]],
    *,
    specs: Sequence[StructureSpec] = DEFAULT_STRUCTURE_SPECS,
    replicates: int = 3,
) -> dict[str, Any]:
    oracle_pass = all(
        item["oracle"]["passes_expected_behavior"]
        and item["oracle"]["boundary_certificates_valid"]
        for item in deterministic_states
    )

    state_by_spec = {item["spec"]["spec_id"]: item["state"] for item in deterministic_states}
    oracle_by_spec = {item["spec"]["spec_id"]: item["oracle"] for item in deterministic_states}

    grouped: dict[str, list[list[float]]] = {}
    for obs in observations:
        sid = str(obs["spec_id"])
        pres = obs.get("provider", {})
        vec = pres.get("vector")
        if vec is not None:
            grouped.setdefault(sid, []).append([float(x) for x in vec])

    expected_ids = {s.spec_id for s in specs}
    provider_complete = all(len(grouped.get(sid, [])) == replicates for sid in expected_ids)

    if not provider_complete:
        return {
            "oracle_pass": oracle_pass,
            "provider_complete": False,
            "verdict": "INCOMPLETE_OBSERVATIONS",
        }

    # Within-state repeatability noise floor
    within_state_noises: list[float] = []
    for sid in expected_ids:
        reps = grouped[sid]
        mean_v = [sum(col) / len(reps) for col in zip(*reps)]
        for rep in reps:
            diff = [a - b for a, b in zip(rep, mean_v)]
            within_state_noises.append(float(np.linalg.norm(diff)))
    noise_floor = median(within_state_noises) if within_state_noises else 0.0
    eff_noise = max(noise_floor, 0.010)

    spec_means = {
        sid: np.mean(grouped[sid], axis=0)
        for sid in expected_ids
    }

    v_base = spec_means["base_nominal"]

    # -------------------------------------------------------------
    # 1. Phase 4A Evaluation: Identity
    # -------------------------------------------------------------
    phase_4a_results: dict[str, Any] = {}
    phase_4a_defects_eta: list[float] = []
    phase_4a_state_matches = True
    phase_4a_trace_distinct = True

    for m in ("authority", "evidence", "temporal"):
        tag = m[:3]
        s_pure = state_by_spec[f"pure_{m[0].upper() if m != 'adversarial' else 'Adv'}"]
        s_left = state_by_spec[f"idem_I_{tag}_left"]
        s_right = state_by_spec[f"idem_I_{tag}_right"]

        o_pure = oracle_by_spec[f"pure_{m[0].upper() if m != 'adversarial' else 'Adv'}"]
        o_left = oracle_by_spec[f"idem_I_{tag}_left"]
        o_right = oracle_by_spec[f"idem_I_{tag}_right"]

        # Deterministic state equality
        match = (s_pure == s_left == s_right)
        phase_4a_state_matches = phase_4a_state_matches and match

        # Provenance trace distinctness
        trace_diff = (o_left["trace_info"] != o_pure["trace_info"]) and (o_right["trace_info"] != o_pure["trace_info"])
        phase_4a_trace_distinct = phase_4a_trace_distinct and trace_diff

        # JEV observational defect
        v_pure = spec_means[f"pure_{m[0].upper() if m != 'adversarial' else 'Adv'}"]
        v_left = spec_means[f"idem_I_{tag}_left"]
        v_right = spec_means[f"idem_I_{tag}_right"]

        d_left = float(np.linalg.norm(v_left - v_pure))
        d_right = float(np.linalg.norm(v_right - v_pure))
        eta_left = d_left / eff_noise
        eta_right = d_right / eff_noise
        phase_4a_defects_eta.extend([eta_left, eta_right])

        phase_4a_results[m] = {
            "operator": m,
            "deterministic_state_matches": match,
            "provenance_trace_distinct": trace_diff,
            "left_identity_defect_ratio_eta": round(eta_left, 2),
            "right_identity_defect_ratio_eta": round(eta_right, 2),
        }

    # -------------------------------------------------------------
    # 2. Phase 4B & 4C Evaluation: 6x6 Matrix & Governance Absorption
    # -------------------------------------------------------------
    mechs = ("authority", "evidence", "causal", "temporal", "resource", "adversarial")
    tags = {"authority": "A", "evidence": "E", "causal": "C", "temporal": "T", "resource": "R", "adversarial": "Adv"}

    matrix_transitions: dict[str, Any] = {}
    fixed_point_matches = 0  # Count of F_j(x_i) == x_i
    all_in_absorbing_class = True
    macrostate_vectors: list[np.ndarray] = []

    for mi in mechs:
        ti = tags[mi]
        s_i = state_by_spec[f"pure_{ti}"]
        v_i = spec_means[f"pure_{ti}"]
        macrostate_vectors.append(v_i)

        for mj in mechs:
            tj = tags[mj]
            if mi == mj:
                # Diagonal: F_i(x_i) = x_i
                fixed_point_matches += 1
            else:
                s_ij = state_by_spec[f"mat_{tj}_{ti}"]
                o_ij = oracle_by_spec[f"mat_{tj}_{ti}"]
                v_ij = spec_means[f"mat_{tj}_{ti}"]
                macrostate_vectors.append(v_ij)

                is_fp = (s_ij == s_i)
                if is_fp:
                    fixed_point_matches += 1

                in_abs = o_ij["governance_class"]["in_absorbing_class"]
                all_in_absorbing_class = all_in_absorbing_class and in_abs

                matrix_transitions[f"{tj}_{ti}"] = {
                    "source": mi,
                    "target_operator": mj,
                    "is_microstate_fixed_point": is_fp,
                    "in_governance_absorbing_class": in_abs,
                    "transition_defect_norm": round(float(np.linalg.norm(v_ij - v_i)), 4),
                }

    # Macrostate class diameter in JEV observer space
    pair_distances: list[float] = []
    base_distances: list[float] = []
    for i in range(len(macrostate_vectors)):
        base_distances.append(float(np.linalg.norm(macrostate_vectors[i] - v_base)))
        for j in range(i + 1, len(macrostate_vectors)):
            pair_distances.append(float(np.linalg.norm(macrostate_vectors[i] - macrostate_vectors[j])))

    class_diameter = max(pair_distances) if pair_distances else 0.0
    mean_pair_distance = float(np.mean(pair_distances)) if pair_distances else 0.0
    min_base_jump = min(base_distances) if base_distances else 0.0
    mean_base_jump = float(np.mean(base_distances)) if base_distances else 0.0

    # -------------------------------------------------------------
    # 3. Phase 4D Evaluation: Zero Transformation Z
    # -------------------------------------------------------------
    phase_4d_results: dict[str, Any] = {}
    phase_4d_defects_eta: list[float] = []
    phase_4d_state_matches = True

    s_Z = state_by_spec["zero_Z"]
    v_Z = spec_means["zero_Z"]

    for m in ("authority", "evidence", "temporal"):
        tag = m[:3]
        s_z_left = state_by_spec[f"zero_Z_{tag}_left"]
        s_z_right = state_by_spec[f"zero_Z_{tag}_right"]

        match_left = (s_z_left == s_Z)
        match_right = (s_z_right == s_Z)
        phase_4d_state_matches = phase_4d_state_matches and match_left and match_right

        v_z_left = spec_means[f"zero_Z_{tag}_left"]
        v_z_right = spec_means[f"zero_Z_{tag}_right"]

        d_z_left = float(np.linalg.norm(v_z_left - v_Z))
        d_z_right = float(np.linalg.norm(v_z_right - v_Z))
        eta_z_left = d_z_left / eff_noise
        eta_z_right = d_z_right / eff_noise
        phase_4d_defects_eta.extend([eta_z_left, eta_z_right])

        phase_4d_results[m] = {
            "operator": m,
            "left_zero_state_matches": match_left,
            "right_zero_state_matches": match_right,
            "left_zero_defect_ratio_eta": round(eta_z_left, 2),
            "right_zero_defect_ratio_eta": round(eta_z_right, 2),
        }

    # -------------------------------------------------------------
    # 4. Phase 4E Evaluation: Product Idempotence / Band Test
    # -------------------------------------------------------------
    phase_4e_results: dict[str, Any] = {}
    phase_4e_defects_eta: list[float] = []
    phase_4e_state_matches = True

    # Test pairs
    test_pairs = [
        ("authority", "evidence"),
        ("evidence", "authority"),
        ("authority", "causal"),
        ("causal", "authority"),
        ("evidence", "resource"),
        ("resource", "evidence"),
    ]
    for m1, m2 in test_pairs:
        t1, t2 = tags[m1], tags[m2]
        s_p = state_by_spec[f"mat_{t1}_{t2}"]
        s_p_sq = state_by_spec[f"prod_sq_{t1}{t2}"]

        match_p = (s_p == s_p_sq)
        phase_4e_state_matches = phase_4e_state_matches and match_p

        v_p = spec_means[f"mat_{t1}_{t2}"]
        v_p_sq = spec_means[f"prod_sq_{t1}{t2}"]

        d_p = float(np.linalg.norm(v_p_sq - v_p))
        eta_p = d_p / eff_noise
        phase_4e_defects_eta.append(eta_p)

        phase_4e_results[f"{t1}{t2}"] = {
            "product": f"({t1} o {t2})",
            "deterministic_idempotence_matches": match_p,
            "product_idempotence_defect_norm": round(d_p, 4),
            "product_idempotence_defect_ratio_eta": round(eta_p, 2),
            "is_product_idempotent": bool(eta_p <= 2.00),
        }

    # Test triples
    test_triples = [
        ("authority", "evidence", "temporal"),
        ("evidence", "resource", "adversarial"),
    ]
    for m1, m2, m3 in test_triples:
        t1, t2, t3 = tags[m1], tags[m2], tags[m3]
        s_p = state_by_spec[f"prod_{t1}{t2}{t3}"]
        s_p_sq = state_by_spec[f"prod_sq_{t1}{t2}{t3}"]

        match_p = (s_p == s_p_sq)
        phase_4e_state_matches = phase_4e_state_matches and match_p

        v_p = spec_means[f"prod_{t1}{t2}{t3}"]
        v_p_sq = spec_means[f"prod_sq_{t1}{t2}{t3}"]

        d_p = float(np.linalg.norm(v_p_sq - v_p))
        eta_p = d_p / eff_noise
        phase_4e_defects_eta.append(eta_p)

        phase_4e_results[f"{t1}{t2}{t3}"] = {
            "product": f"({t1} o {t2} o {t3})",
            "deterministic_idempotence_matches": match_p,
            "product_idempotence_defect_norm": round(d_p, 4),
            "product_idempotence_defect_ratio_eta": round(eta_p, 2),
            "is_product_idempotent": bool(eta_p <= 2.00),
        }

    # -------------------------------------------------------------
    # Gates and Algebraic Characterization
    # -------------------------------------------------------------
    gate_U0 = oracle_pass
    gate_U1_identity = phase_4a_state_matches and phase_4a_trace_distinct
    gate_U2_absorption = all_in_absorbing_class and (fixed_point_matches == 6)  # Only diagonal fixed points
    gate_U3_zero = phase_4d_state_matches
    gate_U4_band = phase_4e_state_matches

    mean_eta_4a = float(np.mean(phase_4a_defects_eta))
    mean_eta_4d = float(np.mean(phase_4d_defects_eta))
    mean_eta_4e = float(np.mean(phase_4e_defects_eta))

    gate_J0 = bool(noise_floor <= 0.050)
    gate_J1_identity = bool(mean_eta_4a <= 1.50)
    gate_J2_zero = bool(mean_eta_4d <= 1.50)
    gate_J3_band = bool(mean_eta_4e <= 1.50)

    gates = {
        "G_U0_oracle_conformance": gate_U0,
        "G_U1_identity_duality_state_vs_trace": gate_U1_identity,
        "G_U2_governance_class_absorption": gate_U2_absorption,
        "G_U3_quotient_zero_transformation": gate_U3_zero,
        "G_U4_product_idempotence_band": gate_U4_band,
        "G_J0_repeatability_noise_floor": gate_J0,
        "G_J1_identity_observational_defect": gate_J1_identity,
        "G_J2_zero_observational_defect": gate_J2_zero,
        "G_J3_band_observational_defect": gate_J3_band,
    }

    supported = all(gates.values())

    # Band characterization
    is_band = gate_U4_band and gate_J3_band

    algebraic_classification = (
        "noncommutative_band_with_zero_and_history_sensitive_provenance"
        if is_band
        else "semigroup_generated_by_idempotents"
    )

    return {
        "oracle_pass": oracle_pass,
        "provider_complete": True,
        "repeatability_noise_floor_sigma_rep": round(noise_floor, 4),
        "effective_noise_floor": round(eff_noise, 4),
        "phase_4a_identity": {
            "results": phase_4a_results,
            "mean_defect_ratio_eta": round(mean_eta_4a, 2),
            "identity_law_satisfied": gate_U1_identity and gate_J1_identity,
            "provenance_erasure_refused": phase_4a_trace_distinct,
        },
        "phase_4b_4c_absorbing_class": {
            "total_matrix_cells": 36,
            "microstate_fixed_points_count": fixed_point_matches,
            "has_universal_microstate_fixed_point": False,
            "all_cells_in_absorbing_governance_class": all_in_absorbing_class,
            "class_diameter_in_observer_space": round(class_diameter, 4),
            "mean_within_class_distance": round(mean_pair_distance, 4),
            "mean_macrostate_breakdown_jump": round(mean_base_jump, 4),
            "class_compactness_ratio": round(class_diameter / max(min_base_jump, eff_noise), 4),
        },
        "phase_4d_zero_transformation": {
            "results": phase_4d_results,
            "mean_defect_ratio_eta": round(mean_eta_4d, 2),
            "quotient_zero_element_confirmed": gate_U3_zero and gate_J2_zero,
        },
        "phase_4e_band_test": {
            "results": phase_4e_results,
            "mean_product_defect_ratio_eta": round(mean_eta_4e, 2),
            "all_products_idempotent": is_band,
            "semigroup_type": "band" if is_band else "semigroup_generated_by_idempotents",
        },
        "gates": gates,
        "supported_within_engineering_gates": supported,
        "verdict": (
            "SEMIGROUP_STRUCTURE_CHARACTERIZED"
            if supported
            else "STRUCTURAL_ANOMALY_DETECTED"
        ),
        "final_mathematical_object": algebraic_classification,
    }


def run_live_structure_experiment(
    *,
    provider: Any,
    specs: Sequence[StructureSpec] = DEFAULT_STRUCTURE_SPECS,
    replicates: int = 3,
) -> dict[str, Any]:
    deterministic_states = build_structure_states(specs)
    questions = question_payload()
    observations: list[dict[str, Any]] = []
    total_calls = len(deterministic_states) * replicates

    for item in deterministic_states:
        sid = str(item["spec"]["spec_id"])
        phase = str(item["spec"]["phase"])
        mode = str(item["spec"]["mode"])
        for rep in range(replicates):
            request_id = f"uow-struct-{sid}-r{rep}"
            provider_res = provider.decide(
                state=dict(item["state"]),
                questions=questions,
                request_id=request_id,
            )
            vec = provider_res.get("vector") or []
            v_norm = float(np.linalg.norm(vec)) if vec else 0.0
            print(
                f"[{len(observations) + 1:03d}/{total_calls:03d}] {sid:<20} "
                f"({phase:<18}, {mode:<18}) rep={rep:02d} -> norm={v_norm:.4f}",
                flush=True,
            )
            observations.append(
                {
                    "spec_id": sid,
                    "replicate": rep,
                    "provider": provider_res,
                }
            )

    analysis = analyze_structure_observations(
        deterministic_states,
        observations,
        specs=specs,
        replicates=replicates,
    )

    return {
        "schema_version": SCHEMA_VERSION,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "experiment": "JEV x UoW Transformation Semigroup Structure Campaign (Phase 4)",
        "method": {
            "replicates_per_state": replicates,
            "total_requests": total_calls,
            "specs_count": len(specs),
        },
        "deterministic_states": deterministic_states,
        "observations": observations,
        "analysis": analysis,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run JEV x UoW Transformation Semigroup Structure Campaign (Phase 4)."
    )
    parser.add_argument("--model", default=DEFAULT_JEV_MODEL)
    parser.add_argument("--replicates", type=int, default=3)
    parser.add_argument("--timeout-s", type=float, default=30.0)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    provider = TypeSafeJevProvider(model=args.model, timeout_s=args.timeout_s)
    payload = run_live_structure_experiment(
        provider=provider,
        replicates=args.replicates,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload.get("analysis", payload), indent=2, sort_keys=True))
    print(f"\nWrote: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
