[platformio]
default_envs = esp32s3_p0_a1

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -I include
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
build_unflags = -std=gnu++11

[env:esp32s3_p0_a1]
build_flags =
    ${env.build_flags}
    -DUOW_PROPOSER_CORE=0
    -DUOW_AUTHORITY_CORE=1

[env:esp32s3_p1_a0]
build_flags =
    ${env.build_flags}
    -DUOW_PROPOSER_CORE=1
    -DUOW_AUTHORITY_CORE=0
