"""Economic optimization proposal and authority gate boundary.

Governing Invariant:
    Economic optimizer proposes -> UoW authority certifies -> State changes

Under no circumstances does minimal cost confer transition authority:
    cheapest option != automatic authority
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, Optional, Tuple

from ..contracts import UoW
from ..state import WorldState
from .atomic_cost import AtomicCost


@dataclass(frozen=True)
class EconomicProposal:
    """Proposal generated by an economic scheduling or resource optimization policy.

    The economic optimizer chooses realizations to minimize cost or maximize efficiency,
    but retains zero authority to commit state changes.
    """

    proposal_id: str
    selected_realization_id: str
    projected_cost: AtomicCost
    candidate_uow: UoW
    market_price_quote: Optional[float] = None  # Downstream pricing decision (if any)


@dataclass(frozen=True)
class EconomicAdmissionResult:
    """Outcome of submitting an economic proposal to the UoW authority boundary."""

    proposal_id: str
    admitted: bool
    status: str
    cost_observed: AtomicCost
    resulting_state: Optional[WorldState] = None
    rejection_reason: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "admitted": self.admitted,
            "status": self.status,
            "cost_observed": self.cost_observed.to_dict(),
            "resulting_state": self.resulting_state.to_dict() if self.resulting_state else None,
            "rejection_reason": self.rejection_reason,
        }


def evaluate_economic_proposal(
    proposal: EconomicProposal,
    initial_state: WorldState,
    authority_gate: Callable[[UoW, WorldState], Tuple[bool, Optional[str]]],
) -> EconomicAdmissionResult:
    """Submit an economic proposal through the strict UoW authority gate.

    The authority gate evaluates contract guards and invariants independently of cost.
    Even a zero-cost or negative-cost proposal will fail closed if unauthorized.
    """
    is_valid, reason = authority_gate(proposal.candidate_uow, initial_state)

    if not is_valid:
        return EconomicAdmissionResult(
            proposal_id=proposal.proposal_id,
            admitted=False,
            status="REJECTED_BY_AUTHORITY",
            cost_observed=proposal.projected_cost,
            resulting_state=initial_state,
            rejection_reason=reason or "Authority gate rejected proposal: guard or invariant violation",
        )

    # Authority certified: apply transition
    _, route = proposal.candidate_uow.Gamma.select_route(initial_state)
    new_state = route.apply_mutations(initial_state)

    return EconomicAdmissionResult(
        proposal_id=proposal.proposal_id,
        admitted=True,
        status="COMMITTED",
        cost_observed=proposal.projected_cost,
        resulting_state=new_state,
        rejection_reason=None,
    )
